[terminal.shell]
program = "/Users/tobydavis/.nix-profile/bin/fish"

[font]
size = 11.0

[font.normal]
family = "MonaSpiceNe Nerd Font"
style = "Light"

[font.italic]
family = "MonaSpiceNe Nerd Font"
style = "Light Italic"

[font.bold]
family = "MonaSpiceNe Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[window]
option_as_alt = "both"
