-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- vim.height = 2
-- vim.opt.showmode = true
-- vim.opt.cmdheight = 2
--
-- autocmd("RecordingEnter", {
--   callback = function()
--     vim.opt.cmdheight = 1
--     -- neovim 9:
--     -- The below vim.notify allows the 'recording @' message to show up if used more than once. if using cmdheight=0
--     vim.notify("this does nothing", vim.log.levels.OFF, {})
--   end,
-- })
